version: '3.8'

services:
  api:
    image: ghcr.io/deefyouknow/nextjs-university-project:latest     
    container_name: reacty    
    env_file:
      - .env
      
    ports:
      - "${APP_PORT}:3000"
    command: npm run start
    restart: unless-stopped
    networks:
      - tunnel-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-web
    # command: tunnel --no-autoupdate run --url http://api:3000
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN_KEY}
    networks:
      - tunnel-net
    restart: unless-stopped

networks:
  tunnel-net:
    driver: bridge
