version: '3.8'

services:
  api:
    image: node:20-alpine
    container_name: reacty
    working_dir: /app
    volumes:
      - ./:/app
      # - /app/node_modules   # uncomment ถ้ามีปัญหาเวลา npm run dev    
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000
    command: sh -c "npm install && npm run build && npm run start"
    restart: unless-stopped
    networks:
      - tunnel-net
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-web
    command: tunnel --no-autoupdate run --url http://api:3000
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN_KEY}
    networks:
      - tunnel-net
    restart: unless-stopped

networks:
  tunnel-net:
    driver: bridge
