name: CI/CD Build & Deploy

on:
  push:
    branches: [ "main" ] # ทำงานเมื่อ Push เข้า main

permissions:
  contents: read
  packages: write

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Repo
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}:latest
          no-cache: true 

      - name: Copy file to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT_SERVER }}
          source: "docker-compose.yml"
          target: ${{ secrets.PATH_SERVER }}

      # 6. SSH เข้าไปสั่งรัน (Deploy)
      - name: Run Docker on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT_SERVER }}
          script: |
            cd ${{ secrets.PATH_SERVER }}
            export GITHUB_REPOSITORY="${{ github.repository }}"
            export REPO_LOWER=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
            
            docker compose pull
            
            docker compose up -d --force-recreate --remove-orphans
            
            docker image prune -f
